# Generated by Django 5.2.1 on 2025-07-02 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('moto_vendida', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_pre_venda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='PreVenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(help_text='Nome simples do cliente', max_length=100)),
                ('telefone', models.CharField(help_text='Telefone com máscara básica', max_length=20)),
                ('moto_desejada', models.CharField(help_text='Moto que o cliente demonstrou interesse', max_length=200)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('convertida', 'Convertida'), ('descartada', 'Descartada')], default='aberta', max_length=20)),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pre_vendas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_venda', to='pre_venda.venda')),
            ],
            options={
                'verbose_name': 'Pré-Venda',
                'verbose_name_plural': 'Pré-Vendas',
                'ordering': ['-data_atendimento'],
            },
        ),
    ]
