# Generated by Django 5.2.1 on 2025-07-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_venda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevenda',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'usuario_sistema__perfil__nome__in': ['vendedor', 'gerente']}, on_delete=django.db.models.deletion.CASCADE, related_name='pre_vendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'usuario_sistema__perfil__nome__in': ['vendedor', 'gerente']}, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_pre_venda', to=settings.AUTH_USER_MODEL),
        ),
    ]
