# Generated by Django 5.2.1 on 2025-07-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_venda', '0002_alter_prevenda_vendedor_alter_venda_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevenda',
            name='venda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
