# Generated by Django 5.2.1 on 2025-07-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_motocicleta_seguro'),
        ('pre_venda', '0003_remove_prevenda_venda_delete_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevenda',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'perfil__nome__in': ['vendedor', 'gerente']}, on_delete=django.db.models.deletion.CASCADE, related_name='pre_vendas', to='core.usuario'),
        ),
    ]
