# Generated by Django 5.2.1 on 2025-06-27 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Saída')),
                ('data_retorno', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Retorno')),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('devolvida', 'Devolvida'), ('atraso', 'Em atraso')], default='aberto', max_length=20, verbose_name='Status')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
                ('motocicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.motocicleta', verbose_name='Motocicleta')),
            ],
        ),
    ]
