# Generated by Django 5.2.1 on 2025-06-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_bem', models.CharField(choices=[('motocicleta', 'Motocicleta'), ('automovel', 'Automóvel'), ('caminhao', 'Caminhão'), ('casa', 'Casa'), ('apartamento', 'Apartamento'), ('empresa', 'Empresa'), ('vida', 'Vida'), ('saude', 'Saúde'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('comissao_padrao', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano de Seguro',
                'verbose_name_plural': 'Planos de Seguro',
            },
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
            },
        ),
        migrations.RemoveField(
            model_name='cotacaoseguro',
            name='moto',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='comissao',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='moto',
        ),
        migrations.AddField(
            model_name='cotacaoseguro',
            name='comissao_percentual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotacaoseguro',
            name='plano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motocicleta',
            name='seguro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motocicleta', to='core.seguro'),
        ),
        migrations.AddField(
            model_name='seguro',
            name='comissao_percentual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguro',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso'), ('vencido', 'Vencido')], default='ativo', max_length=20),
        ),
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('motocicleta', 'Motocicleta'), ('automovel', 'Automóvel'), ('caminhao', 'Caminhão'), ('casa', 'Casa'), ('apartamento', 'Apartamento'), ('empresa', 'Empresa'), ('vida', 'Vida'), ('saude', 'Saúde'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('placa', models.CharField(blank=True, max_length=8, null=True)),
                ('chassi', models.CharField(blank=True, max_length=17, null=True)),
                ('renavam', models.CharField(blank=True, max_length=11, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Bem',
                'verbose_name_plural': 'Bens',
            },
        ),
        migrations.AddField(
            model_name='cotacaoseguro',
            name='bem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bem'),
        ),
        migrations.AddField(
            model_name='seguro',
            name='bem',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='core.bem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguro',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='core.planoseguro'),
        ),
        migrations.AddField(
            model_name='planoseguro',
            name='seguradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.seguradora'),
        ),
    ]
