# Generated by Django 5.2.1 on 2025-06-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcoes', models.JSONField(default=dict)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.perfil')),
            ],
        ),
    ]
