# Generated by Django 5.2.1 on 2025-06-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuperfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuperfil',
            options={'verbose_name': 'Menu por Perfil', 'verbose_name_plural': 'Menus por Perfil'},
        ),
        migrations.RemoveField(
            model_name='menuperfil',
            name='opcoes',
        ),
        migrations.AddField(
            model_name='menuperfil',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuperfil',
            name='modulo',
            field=models.CharField(default='clientes', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuperfil',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil'),
        ),
    ]
