# Generated by Django 5.2.1 on 2025-06-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dummymodel_planoseguro_seguradora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('incidente', 'Incidente'), ('problema_tecnico', 'Problema Técnico'), ('solicitacao', 'Solicitação'), ('reclamacao', 'Reclamação'), ('sugestao', 'Sugestão'), ('manutencao', 'Manutenção'), ('seguranca', 'Segurança'), ('outros', 'Outros')], max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('em_andamento', 'Em Andamento'), ('resolvida', 'Resolvida'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('solucao', models.TextField(blank=True, null=True)),
                ('arquivos_anexos', models.FileField(blank=True, null=True, upload_to='ocorrencias/')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.loja')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_responsavel', to='core.usuario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_solicitadas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('privado', models.BooleanField(default=False, help_text='Comentário visível apenas para administradores')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_ocorrencias', to='core.usuario')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.ocorrencia')),
            ],
            options={
                'verbose_name': 'Comentário de Ocorrência',
                'verbose_name_plural': 'Comentários de Ocorrências',
                'ordering': ['data_criacao'],
            },
        ),
    ]
