# Generated by Django 5.2.1 on 2025-06-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ocorrencia_comentarioocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='motocicleta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
