# Generated by Django 5.2.1 on 2025-06-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menuperfil_options_remove_menuperfil_opcoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuperfil',
            name='modulo',
            field=models.CharField(max_length=50),
        ),
    ]
