# Generated by Django 5.2.1 on 2025-06-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_menuperfil_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_usuario', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Menu por Usuário',
                'verbose_name_plural': 'Menus por Usuário',
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
