# Generated by Django 5.2.1 on 2025-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menuusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='motocicleta',
            name='ano_fabricacao',
            field=models.CharField(blank=True, help_text='Ano de fabricação (quando diferente do ano do modelo)', max_length=4, null=True),
        ),
    ]
