# Generated by Django 5.2.1 on 2025-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_motocicleta_ano_fabricacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='valor_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='valor_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
