# Generated by Django 5.2.1 on 2025-06-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_motocicleta_valor_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motocicleta',
            name='rodagem',
            field=models.IntegerField(blank=True, help_text='Quilometragem atual da motocicleta (em km)', null=True),
        ),
    ]
