# Generated by Django 5.2.1 on 2025-06-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_motocicleta_rodagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='status',
            field=models.CharField(choices=[('estoque', 'Em Estoque'), ('vendida', 'Vendida'), ('repasse', 'Repasse'), ('reservada', 'Reservada'), ('manutencao', 'Em Manutenção'), ('pendencia', 'Pendência'), ('bloqueada', 'Bloqueada')], default='estoque', max_length=20),
        ),
    ]
