# Generated by Django 5.2.1 on 2025-07-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_motocicleta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicoproprietario',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('consignacao', 'Consignação'), ('repasse', 'Repasse'), ('remocao', 'Remoção Manual'), ('exclusao_cliente', 'Exclusão do Cliente')], max_length=20),
        ),
    ]
