# Generated by Django 5.2.1 on 2025-07-01 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('marketing', 'Marketing'), ('salario', 'Salário'), ('energia', 'Energia'), ('agua', 'Água'), ('internet', 'Internet'), ('telefone', 'Telefone'), ('manutencao', 'Manutenção'), ('combustivel', 'Combustível'), ('impostos', 'Impostos'), ('seguros', 'Seguros'), ('fornecedores', 'Fornecedores'), ('outros', 'Outros')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('fixa_variavel', models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], default='variavel', max_length=20)),
                ('centro_custo', models.CharField(blank=True, help_text='Ex: Oficina, Loja 1, Delivery', max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.loja')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_registradas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ReceitaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_extras', to='core.loja')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_registradas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Receita Extra',
                'verbose_name_plural': 'Receitas Extras',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20)),
                ('referente_a', models.CharField(choices=[('venda', 'Venda'), ('despesa', 'Despesa'), ('receita_extra', 'Receita Extra'), ('outros', 'Outros')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.despesa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.loja')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_registrados', to='core.usuario')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.venda')),
                ('receita_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.receitaextra')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='VendaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('produto', models.CharField(help_text='Descrição do produto vendido', max_length=200)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, help_text='Custo de aquisição do produto', max_digits=10)),
                ('canal_venda', models.CharField(choices=[('loja', 'Loja Física'), ('olx', 'OLX'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('site', 'Site'), ('telefone', 'Telefone'), ('indicacao', 'Indicação'), ('outros', 'Outros')], default='loja', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_financeiras', to='core.motocicleta')),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='core.venda')),
            ],
            options={
                'verbose_name': 'Venda Financeira',
                'verbose_name_plural': 'Vendas Financeiras',
                'ordering': ['-data'],
            },
        ),
    ]
