# Generated by Django 5.2.1 on 2025-07-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_vendafinanceira_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='comunicacao_documentacao_enviada',
            field=models.BooleanField(default=False, help_text='Se a comunicação de documentação foi enviada'),
        ),
        migrations.AddField(
            model_name='venda',
            name='comunicacao_entrega_enviada',
            field=models.BooleanField(default=False, help_text='Se a comunicação de entrega foi enviada'),
        ),
        migrations.AddField(
            model_name='venda',
            name='comunicacao_intencao_enviada',
            field=models.BooleanField(default=False, help_text='Se a comunicação de intenção de venda foi enviada'),
        ),
        migrations.AddField(
            model_name='venda',
            name='comunicacao_pagamento_enviada',
            field=models.BooleanField(default=False, help_text='Se a comunicação de confirmação de pagamento foi enviada'),
        ),
        migrations.CreateModel(
            name='ComunicacaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('intencao', 'Intenção de Venda'), ('confirmacao_pagamento', 'Confirmação de Pagamento'), ('documentacao', 'Documentação'), ('entrega', 'Entrega'), ('outros', 'Outros')], max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('obrigatoria', models.BooleanField(default=True, help_text='Se esta comunicação é obrigatória para a venda')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('destinatario', models.CharField(help_text='Nome do destinatário da comunicação', max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('prazo_limite', models.DateTimeField(blank=True, help_text='Prazo limite para envio da comunicação', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes_venda', to='core.usuario')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes', to='core.venda')),
            ],
            options={
                'verbose_name': 'Comunicação de Venda',
                'verbose_name_plural': 'Comunicações de Venda',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
