# Generated by Django 5.2.1 on 2025-07-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_venda_comunicacao_documentacao_enviada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL para ação ou detalhe', max_length=300, null=True)),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('ocorrencia', 'Ocorrência'), ('documento', 'Documento'), ('menção', 'Menção'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
