# Generated by Django 5.2.1 on 2025-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacaovenda',
            name='comprovante_envio',
            field=models.FileField(blank=True, help_text='Comprovante de envio da comunicação', null=True, upload_to='comunicacoes/comprovantes/'),
        ),
        migrations.AddField(
            model_name='comunicacaovenda',
            name='documento_anexo',
            field=models.FileField(blank=True, help_text='Documento da comunicação (PDF, imagem, etc.)', null=True, upload_to='comunicacoes/documentos/'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('venda', 'Venda'), ('ocorrencia', 'Ocorrência'), ('documento', 'Documento'), ('menção', 'Menção'), ('venda_pendente', 'Venda Pendente'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
