# Generated by Django 5.2.1 on 2025-07-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comunicacaovenda_comprovante_envio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motocicleta',
            name='seguro',
        ),
    ]
