# Generated by Django 5.2.1 on 2025-07-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_motocicleta_seguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('consultor', 'Consultor'), ('financeiro', 'Financeiro'), ('ti', 'TI'), ('recepcionista', 'Recepcionista')], max_length=50, unique=True),
        ),
    ]
