# Generated by Django 5.2.1 on 2025-07-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_perfil_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoMotocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('consignacao', 'Consignação'), ('ficha_cliente', 'Ficha do Cliente'), ('recibo', 'Recibo'), ('seguro', 'Seguro'), ('financiamento', 'Financiamento'), ('intencao_venda', 'Intenção de Compra/Venda'), ('outro', 'Outro')], max_length=30)),
                ('arquivo', models.FileField(upload_to='documentos_motos/')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.motocicleta')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.venda')),
            ],
            options={
                'verbose_name': 'Documento de Motocicleta',
                'verbose_name_plural': 'Documentos de Motocicletas',
                'ordering': ['-data_upload'],
            },
        ),
    ]
